"""empty message

Revision ID: 055adf04eeae
Revises: 
Create Date: 2019-09-09 20:55:29.185588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055adf04eeae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
